alsqja/Connect

src/main/java/com/example/connect/domain/user/repository/UserRepository.java, src/main/java/com/example/connect/global/common/dto/TokenDto.java, src/main/java/com/example/connect/global/config/SecurityConfig.java, src/main/java/com/example/connect/global/config/WebConfig.java, src/main/java/com/example/connect/global/config/auth/DelegatedAccessDeniedHandler.java, src/main/java/com/example/connect/global/config/auth/DelegatedAuthenticationEntryPoint.java, src/main/java/com/example/connect/global/config/auth/UserDetailsImpl.java, src/main/java/com/example/connect/global/config/auth/UserDetailsServiceImpl.java, src/main/java/com/example/connect/global/config/filter/JwtAuthFilter.java, src/main/java/com/example/connect/global/enums/AuthenticationScheme.java, src/main/java/com/example/connect/global/enums/UserRole.java, src/main/java/com/example/connect/global/util/JwtProvider.java
- (UserDetailsImpl) authentication.getPrincipal().getUser() 로 토큰 유저정보 받기 가능
#30
=> feat: spring security 설정 추가

src/main/java/com/example/connect/domain/address/entity/Address.java, src/main/java/com/example/connect/domain/user/controller/AuthController.java, src/main/java/com/example/connect/domain/user/dto/SignupServiceDto.java, src/main/java/com/example/connect/domain/user/dto/UserReqDto.java, src/main/java/com/example/connect/domain/user/dto/UserResDto.java, src/main/java/com/example/connect/domain/user/entity/User.java, src/main/java/com/example/connect/domain/user/repository/UserRepository.java, src/main/java/com/example/connect/domain/user/service/AuthService.java, src/main/java/com/example/connect/global/config/DataInitializer.java, src/main/java/com/example/connect/global/error/errorcode/ErrorCode.java
- SQLRestriction 필터 제외를 위해 native query 사용하여 email 존재 여부 확인
- controller->service 데이터 이동을 위해 SignupServiceDto 생성 후 사용
- user entity 생성자 status 값 제외 수정
#1
=> feat: signup 추가

src/main/java/com/example/connect/domain/user/controller/UserController.java, src/main/java/com/example/connect/domain/user/dto/PasswordReqDto.java, src/main/java/com/example/connect/domain/user/service/UserService.java, src/main/java/com/example/connect/global/common/Const.java, src/main/java/com/example/connect/global/config/auth/UserDetailsServiceImpl.java
- 비밀번호 확인 성공 시 쿠키 설정
- 해당 쿠키 보유 시 유저 삭제 가능
#13
=> feat: 비밀번호 확인 로직 추가

src/main/java/com/example/connect/domain/category/controller/AdminCategoryController.java, src/main/java/com/example/connect/domain/category/service/AdminCategoryService.java
=> feat: 카테고리 삭제 기능

build.gradle, src/main/java/com/example/connect/domain/file/controller/FileController.java, src/main/java/com/example/connect/domain/file/dto/UrlReqDto.java, src/main/java/com/example/connect/domain/file/dto/UrlResDto.java, src/main/java/com/example/connect/domain/file/service/FileService.java, src/main/java/com/example/connect/global/config/WebConfig.java, src/main/resources/application.properties
- S3 url 생성
- 클라이언트 구현 시 contentType 설정 필요
#71
=> feat: 파일 업로드 url 생성 요청 추가

src/main/java/com/example/connect/domain/file/controller/FileController.java, src/main/java/com/example/connect/domain/file/dto/UrlResDto.java, src/main/java/com/example/connect/domain/file/service/FileService.java
=> fix: post file-url response dto 변경

src/main/java/com/example/connect/domain/membership/entity/Membership.java, src/main/java/com/example/connect/domain/membership/repository/MembershipRepository.java, src/main/java/com/example/connect/domain/user/controller/AdminUserController.java, src/main/java/com/example/connect/domain/user/dto/AdminUserListResDto.java, src/main/java/com/example/connect/domain/user/dto/AdminUserResDto.java, src/main/java/com/example/connect/domain/user/dto/RedisUserDto.java, src/main/java/com/example/connect/domain/user/repository/UserRepository.java, src/main/java/com/example/connect/domain/user/service/AdminUserService.java, src/main/java/com/example/connect/domain/user/service/AuthService.java, src/main/java/com/example/connect/domain/user/service/UserService.java, src/main/java/com/example/connect/global/config/DataInitializer.java, src/main/java/com/example/connect/global/config/auth/UserDetailsServiceImpl.java
- 유저 전체 조회 기능 구현
- Membership expiredAt -> expiredDate 로 변경
#17
=> feat: 관리자 유저 전체 조회

src/main/java/com/example/connect/domain/subcategory/controller/AdminSubCategoryController.java, src/main/java/com/example/connect/domain/subcategory/service/AdminSubCategoryService.java
=> feat: 서브 카테고리 삭제 기능

src/main/java/com/example/connect/domain/category/controller/CategoryController.java, src/main/java/com/example/connect/domain/category/dto/AllCategoriesResDto.java, src/main/java/com/example/connect/domain/category/service/CategoryService.java
=> feat: 카테고리, 서브 카테고리 전체 조회

build.gradle, src/main/java/com/example/connect/domain/payment/controller/PaymentController.java, src/main/java/com/example/connect/domain/payment/dto/PaidPaymentAmountDto.java, src/main/java/com/example/connect/domain/payment/dto/PaidPaymentResDto.java, src/main/java/com/example/connect/domain/payment/dto/PaymentCancelReqDto.java, src/main/java/com/example/connect/domain/payment/dto/PaymentReqDto.java, src/main/java/com/example/connect/domain/payment/dto/PaymentResDto.java, src/main/java/com/example/connect/domain/payment/dto/PortoneToken.java, src/main/java/com/example/connect/domain/payment/entity/Payment.java, src/main/java/com/example/connect/domain/payment/repository/PaymentRepository.java, src/main/java/com/example/connect/domain/payment/service/PaymentService.java, src/main/java/com/example/connect/domain/payment/service/PortoneService.java, src/main/java/com/example/connect/domain/point/entity/Point.java, src/main/java/com/example/connect/global/config/DataInitializer.java, src/main/java/com/example/connect/global/enums/PaymentStatus.java, src/main/java/com/example/connect/global/enums/PaymentType.java, src/main/java/com/example/connect/global/error/errorcode/ErrorCode.java, src/main/resources/application.properties
portone 나이스 페이먼츠와 연동
프론트 없을 경우 테스트 힘듦 (프론트 업데이트 예정)
포인트와 연관되어 포인트 내용 추가가 진행 되고 있습니다만 내부 로직에 관해서 수정사항 발생 할 것 같습니다.
todo:
결제 error code 추가
결제 조회 기능 추가
결제 취소 시 포인트 수거 기능 추가
Issue - #5
=> feat: 결제 내역 저장 및 취소 기능 구현

src/main/java/com/example/connect/domain/match/controller/MatchingController.java, src/main/java/com/example/connect/domain/match/repository/MatchingRepository.java, src/main/java/com/example/connect/domain/match/service/MatchingService.java, src/main/java/com/example/connect/domain/schedule/controller/ScheduleController.java, src/main/java/com/example/connect/domain/schedule/dto/ScheduleReqDto.java, src/main/java/com/example/connect/domain/schedule/dto/ScheduleResDto.java, src/main/java/com/example/connect/domain/schedule/dto/ScheduleServiceDto.java, src/main/java/com/example/connect/domain/schedule/entity/Schedule.java, src/main/java/com/example/connect/domain/schedule/repository/ScheduleRepository.java, src/main/java/com/example/connect/domain/schedule/service/ScheduleService.java, src/main/java/com/example/connect/domain/schedulesubcategory/dto/ContentDescriptionDto.java, src/main/java/com/example/connect/domain/schedulesubcategory/entity/ScheduleSubCategory.java, src/main/java/com/example/connect/global/config/DataInitializer.java
- 같은 날 일정 있을 때 throw
- subCategoryId 없는 값 throw
#25
=> feat: 일정 생성 추가

src/main/java/com/example/connect/domain/report/controller/ReportController.java, src/main/java/com/example/connect/domain/report/dto/ReportReqDto.java, src/main/java/com/example/connect/domain/report/dto/ReportResDto.java, src/main/java/com/example/connect/domain/report/repository/ReportRepository.java, src/main/java/com/example/connect/domain/report/service/ReportService.java
=> feat: 신고하기

src/main/java/com/example/connect/domain/schedule/controller/ScheduleController.java, src/main/java/com/example/connect/domain/schedule/service/ScheduleService.java
=> feat: 일정 삭제 추가

src/main/java/com/example/connect/domain/report/controller/ReportController.java, src/main/java/com/example/connect/domain/report/service/ReportService.java, src/main/java/com/example/connect/domain/user/entity/User.java
=> feat: 신고 취소 기능

src/main/java/com/example/connect/domain/report/controller/AdminReportController.java, src/main/java/com/example/connect/domain/report/service/AdminReportService.java
=> feature: 신고 삭제 기능

src/main/java/com/example/connect/domain/payment/dto/PaymentGetResDto.java, src/main/java/com/example/connect/domain/payment/repository/PaymentRepository.java, src/main/java/com/example/connect/domain/payment/service/PaymentService.java
프론트 결제 내역 노출 테이블을 위한 응답값 수정
- 결제 시도 한 사람 email 정보
- 취소 시도를 위한 payment Id 전달
=> fix: payment get 응답값 수정

src/main/java/com/example/connect/domain/schedule/controller/ScheduleController.java, src/main/java/com/example/connect/domain/schedule/dto/ScheduleOnlyResDto.java, src/main/java/com/example/connect/domain/schedule/repository/CustomScheduleRepositoryImpl.java, src/main/java/com/example/connect/domain/schedule/repository/ScheduleRepository.java, src/main/java/com/example/connect/domain/schedule/service/ScheduleService.java
=> feat: 일정 단일 조회

src/main/java/com/example/connect/domain/schedule/controller/ScheduleController.java, src/main/java/com/example/connect/domain/schedule/service/ScheduleService.java, src/main/java/com/example/connect/domain/schedulesubcategory/dto/ScheduleSubCategoryResDto.java, src/main/java/com/example/connect/domain/subcategory/repository/SubCategoryRepository.java, src/main/resources/application.properties
=> feat: 단일 일정 컨텐츠 조회

src/main/java/com/example/connect/domain/match/dto/MatchingListResDto.java, src/main/java/com/example/connect/domain/match/dto/MatchingResDto.java, src/main/java/com/example/connect/domain/match/entity/Matching.java, src/main/java/com/example/connect/domain/match/repository/MatchingRepository.java, src/main/java/com/example/connect/domain/match/service/MatchingService.java, src/main/java/com/example/connect/domain/schedule/controller/ScheduleController.java, src/main/java/com/example/connect/global/config/DataInitializer.java
- add similarity column to matching table 
#44
=> feat: 단일 일정 매칭 조회

src/main/java/com/example/connect/domain/match/controller/MatchingController.java, src/main/java/com/example/connect/domain/match/dto/MatchingResDto.java, src/main/java/com/example/connect/domain/match/dto/MatchingWithScheduleResDto.java, src/main/java/com/example/connect/domain/match/dto/UpdateMatchReqDto.java, src/main/java/com/example/connect/domain/match/entity/Matching.java, src/main/java/com/example/connect/domain/match/service/MatchingService.java, src/main/java/com/example/connect/domain/schedule/controller/ScheduleController.java, src/main/java/com/example/connect/global/enums/MatchStatus.java, src/test/java/com/example/connect/domain/match/service/MatchingServiceTest.java
- 매칭 신청하기와 통합
- status 로 설정
#45
=> feat: 매칭 수정

src/main/java/com/example/connect/domain/payment/service/PaymentService.java, src/main/java/com/example/connect/domain/point/controller/PointController.java, src/main/java/com/example/connect/domain/point/dto/PointUpdateReqDto.java, src/main/java/com/example/connect/domain/point/entity/Point.java, src/main/java/com/example/connect/domain/point/repository/PointRepository.java, src/main/java/com/example/connect/domain/point/service/PointService.java, src/main/java/com/example/connect/domain/pointuse/entity/PointUse.java, src/main/java/com/example/connect/domain/pointuse/repository/PointUseRepository.java, src/main/java/com/example/connect/global/config/DataInitializer.java, src/main/java/com/example/connect/global/enums/PointUseType.java, src/main/java/com/example/connect/global/error/errorcode/ErrorCode.java
=> feat: 포인트 사용 구현

src/main/java/com/example/connect/ConnectApplication.java, src/main/java/com/example/connect/domain/point/repository/PointRepository.java, src/main/java/com/example/connect/domain/point/service/PointService.java, src/main/java/com/example/connect/domain/pointuse/repository/PointUseRepository.java, src/main/java/com/example/connect/global/config/SchedulerConfig.java
=> feat: 포인트 자동 소멸 구현

src/main/java/com/example/connect/domain/match/service/MatchingService.java, src/main/java/com/example/connect/domain/schedule/repository/ScheduleRepository.java
- 신고 내역 존재 시 매칭 검색 안됨
- 동일 스케줄 매칭 존재 시 매칭 검색 안됨
=> fix: 매칭 쿼리 수정

src/main/java/com/example/connect/domain/payment/service/PaymentService.java, src/main/java/com/example/connect/domain/point/repository/PointRepository.java, src/main/java/com/example/connect/domain/pointuse/repository/PointUseRepository.java, src/main/java/com/example/connect/global/error/errorcode/ErrorCode.java
포인트가 사용되었을 경우 취소 불가능
이외의 경우 point isZero = true, point use 환불로 데이터 추가
#9
=> feat: 포인트 사용 추가로 인한 환불 로직 변경

src/main/java/com/example/connect/domain/report/controller/AdminReportController.java, src/main/java/com/example/connect/domain/report/dto/AdminReportResDto.java, src/main/java/com/example/connect/domain/report/repository/ReportRepository.java, src/main/java/com/example/connect/domain/report/service/ReportService.java
=> feature: 신고 내역 조회(관리자) 기능

src/main/java/com/example/connect/domain/point/controller/PointController.java, src/main/java/com/example/connect/domain/point/service/PointService.java, src/main/java/com/example/connect/domain/pointuse/dto/PointUseListResDto.java, src/main/java/com/example/connect/domain/pointuse/dto/PointUseResDto.java, src/main/java/com/example/connect/domain/pointuse/repository/PointUseRepository.java, src/main/java/com/example/connect/domain/user/controller/UserController.java, src/main/java/com/example/connect/domain/user/dto/UserResDto.java, src/main/java/com/example/connect/domain/user/service/UserService.java
[유저 포인트 조회 구현]
- 유저 별 포인트 조회 
- 유저 프로필 조회 -> 소지 포인트 표기
- null 에러 처리
- user 폴더 파일
#12
=> feat: 포인트 조회 기능 구현

build.gradle, src/main/java/com/example/connect/domain/chat/WebsocketEventListener.java, src/main/java/com/example/connect/domain/chat/controller/ChatController.java, src/main/java/com/example/connect/domain/chat/controller/ChattroomController.java, src/main/java/com/example/connect/domain/chat/dto/ChatRequestDto.java, src/main/java/com/example/connect/domain/chat/dto/ChatResponseDto.java, src/main/java/com/example/connect/domain/chat/entity/Chat.java, src/main/java/com/example/connect/domain/chat/entity/Chatroom.java, src/main/java/com/example/connect/domain/chat/entity/UserChatroom.java, src/main/java/com/example/connect/domain/chat/entity/enums/RoomStatus.java, src/main/java/com/example/connect/domain/chat/repository/ChatRepository.java, src/main/java/com/example/connect/domain/chat/repository/ChatroomRepository.java, src/main/java/com/example/connect/domain/chat/repository/UserChatroomRepository.java, src/main/java/com/example/connect/domain/chat/service/ChatService.java, src/main/java/com/example/connect/domain/chat/service/ChatroomService.java, src/main/java/com/example/connect/domain/chat/service/UserChatroomService.java, src/main/java/com/example/connect/global/config/WebConfig.java, src/main/java/com/example/connect/global/config/WebSocketStompConfig.java, src/main/java/com/example/connect/global/config/filter/JwtAuthFilter.java
• 웹소캣 프로토콜이므로 응답 포맷을 맞추지 않고 데이터만 응답 값에 담았습니다.
• 매칭 수락 시 웹소캣이 시작되고 웹소캣 연결 시 EventListener를 통해 채팅방 생성 및 유저 연결 또는 채팅 내역 불러오기가 발생됩니다.
#29 #94
=> feat: 채팅/채팅방 연동 

src/main/java/com/example/connect/domain/user/controller/UserController.java
=> fix: 유저 프로필 주석 해제

src/main/java/com/example/connect/domain/chat/controller/ChatroomController.java, src/main/java/com/example/connect/domain/chat/entity/Chat.java, src/main/java/com/example/connect/domain/chat/repository/ChatRepository.java, src/main/java/com/example/connect/domain/chat/repository/UserChatroomRepository.java, src/main/java/com/example/connect/domain/chat/service/ChatService.java, src/main/java/com/example/connect/domain/chat/service/ChatroomService.java, src/main/java/com/example/connect/domain/chat/service/UserChatroomService.java
=> feat: 채팅방 삭제 API 및 Transactional 명시

src/test/java/com/example/connect/domain/report/service/ReportServiceTest.java, src/test/resources/application.properties
=> test: 신고하기 기능 testcode

src/main/java/com/example/connect/domain/coupon/controller/AdminCouponController.java, src/main/java/com/example/connect/domain/coupon/dto/AdminCouponReqDto.java, src/main/java/com/example/connect/domain/coupon/dto/CouponResDto.java, src/main/java/com/example/connect/domain/coupon/entity/Coupon.java, src/main/java/com/example/connect/domain/coupon/service/AdminCouponService.java, src/main/java/com/example/connect/global/config/DataInitializer.java
=> feat: 쿠폰 생성 기능 구현

src/main/java/com/example/connect/domain/coupon/controller/CouponController.java, src/main/java/com/example/connect/domain/coupon/dto/CouponListResDto.java, src/main/java/com/example/connect/domain/coupon/repository/CouponRepository.java, src/main/java/com/example/connect/domain/coupon/service/AdminCouponService.java, src/main/java/com/example/connect/domain/coupon/service/CouponService.java
=> feat: 쿠폰 단건/다건 조회 구현

src/main/java/com/example/connect/domain/user/service/AuthService.java, src/main/java/com/example/connect/domain/user/service/EmailService.java
=> feat: 존재하는 이메일 확인 로직 이동

src/main/java/com/example/connect/domain/user/entity/User.java, src/main/java/com/example/connect/domain/userimage/controller/UserImageController.java, src/main/java/com/example/connect/domain/userimage/dto/UserImageReqDto.java, src/main/java/com/example/connect/domain/userimage/dto/UserImageResDto.java, src/main/java/com/example/connect/domain/userimage/entity/UserImage.java, src/main/java/com/example/connect/domain/userimage/repository/UserImageRepository.java, src/main/java/com/example/connect/domain/userimage/service/UserImageService.java
=> feat: 이미지 업로드 기능 구현

src/main/java/com/example/connect/domain/userimage/controller/UserImageController.java, src/main/java/com/example/connect/domain/userimage/dto/UserImagePageResDto.java, src/main/java/com/example/connect/domain/userimage/dto/UserImageResDto.java, src/main/java/com/example/connect/domain/userimage/repository/UserImageRepository.java, src/main/java/com/example/connect/domain/userimage/service/UserImageService.java, src/main/java/com/example/connect/global/config/DataInitializer.java
=> feat: 피드 전체 조회

src/main/java/com/example/connect/domain/userimage/controller/UserImageController.java, src/main/java/com/example/connect/domain/userimage/entity/UserImage.java, src/main/java/com/example/connect/domain/userimage/repository/UserImageRepository.java, src/main/java/com/example/connect/domain/userimage/service/UserImageService.java
=> feat: 피드 수정

src/main/java/com/example/connect/domain/userimage/controller/UserImageController.java, src/main/java/com/example/connect/domain/userimage/service/UserImageService.java
=> feat: 피드 삭제

src/main/java/com/example/connect/domain/userimage/controller/UserImageController.java, src/main/java/com/example/connect/domain/userimage/dto/UserImageDetailResDto.java, src/main/java/com/example/connect/domain/userimage/repository/UserImageRepository.java, src/main/java/com/example/connect/domain/userimage/service/UserImageService.java
=> feat: 피드 단일 조회

src/main/java/com/example/connect/domain/coupon/controller/AdminCouponController.java, src/main/java/com/example/connect/domain/coupon/dto/AdminCouponUpdateReqDto.java, src/main/java/com/example/connect/domain/coupon/entity/Coupon.java, src/main/java/com/example/connect/domain/coupon/service/AdminCouponService.java
=> feat: admin 쿠폰 수정 기능 구현

src/main/java/com/example/connect/domain/coupon/controller/CouponController.java, src/main/java/com/example/connect/domain/coupon/dto/CouponUseDto.java, src/main/java/com/example/connect/domain/coupon/service/CouponService.java, src/main/java/com/example/connect/domain/couponuser/dto/CouponUserUseResDto.java, src/main/java/com/example/connect/domain/couponuser/entity/CouponUser.java, src/main/java/com/example/connect/domain/schedule/entity/Schedule.java, src/main/java/com/example/connect/global/error/errorcode/ErrorCode.java
=> feat: 쿠폰 사용 기능 구현

src/main/java/com/example/connect/domain/match/service/MatchingService.java, src/main/java/com/example/connect/domain/user/controller/UserController.java, src/main/java/com/example/connect/domain/user/dto/UserSimpleResDto.java, src/main/java/com/example/connect/domain/user/service/EmailService.java, src/main/java/com/example/connect/domain/user/service/UserService.java, src/main/java/com/example/connect/domain/userimage/repository/UserImageRepository.java, src/main/java/com/example/connect/domain/userimage/service/UserImageService.java, src/main/java/com/example/connect/global/aop/CheckMembershipAspect.java, src/main/java/com/example/connect/global/aop/annotation/CheckMembership.java, src/main/java/com/example/connect/global/common/Const.java
- aop 활용
- 유저 정보 받아오기 profileUrl 적용
- 매칭 찾기 profileUrl 에도 적용
#169
=> feat: 유저 정보 마스킹 적용

src/main/java/com/example/connect/domain/coupon/entity/Coupon.java, src/main/java/com/example/connect/domain/coupon/repository/CouponRepository.java, src/main/java/com/example/connect/domain/coupon/service/CouponService.java, src/main/java/com/example/connect/domain/couponuser/entity/CouponUser.java, src/main/java/com/example/connect/domain/couponuser/repository/CouponUserRepository.java, src/main/java/com/example/connect/global/config/SchedulerConfig.java
=> feat: 소멸기한 만료 쿠폰 삭제

src/main/java/com/example/connect/domain/chat/entity/Chat.java, src/main/java/com/example/connect/domain/chat/repository/ChatRepository.java, src/main/java/com/example/connect/domain/chat/repository/UserChatroomRepository.java, src/main/java/com/example/connect/domain/chat/service/ChatroomService.java
=> fix: 채팅방 삭제 오류 수정

src/main/java/com/example/connect/domain/review/repository/ReviewRepository.java, src/main/java/com/example/connect/domain/user/dto/UserSimpleResDto.java, src/main/java/com/example/connect/domain/user/service/UserService.java
=> refactor: 매칭 리뷰 별점 평균 조회

src/main/java/com/example/connect/domain/match/repository/MatchingRepository.java, src/main/java/com/example/connect/domain/notify/service/SseService.java, src/main/java/com/example/connect/global/aop/CheckMembershipAspect.java, src/main/java/com/example/connect/global/common/Const.java, src/main/java/com/example/connect/global/config/SchedulerConfig.java
- db에만 저장하고 커넥션 연결 시 이벤트 전송
#188
=> feat: 리뷰 알림 기능 추가

src/main/java/com/example/connect/domain/chat/controller/ChatroomController.java, src/main/java/com/example/connect/domain/chat/entity/Chat.java, src/main/java/com/example/connect/domain/chat/entity/UserChatroom.java, src/main/java/com/example/connect/domain/chat/repository/ChatroomRepository.java, src/main/java/com/example/connect/domain/chat/repository/UserChatroomRepository.java, src/main/java/com/example/connect/domain/chat/service/ChatroomService.java
유저가 채팅방 삭제 시, 상태 유저에게 해당 유저의 채팅 기록이 보이지 않는 오류 수정했습니다.
#198
=> fix: 채팅방 삭제 오류 수정2

src/main/java/com/example/connect/domain/chat/repository/UserChatroomRepository.java, src/main/java/com/example/connect/domain/chat/service/ChatService.java, src/main/java/com/example/connect/domain/chat/service/ChatroomService.java, src/main/java/com/example/connect/domain/chat/service/UserChatroomService.java
채팅방 삭제 이후, 삭제된 채팅에 접근 가능한 오류를 예외처리 했습니다.
[#200](https://github.com/alsqja/Connect/issues/200)
=> fix: 채팅방 삭제 후 채팅 내역 조회 예외처러 수정

src/main/java/com/example/connect/domain/membership/controller/MembershipController.java, src/main/java/com/example/connect/domain/membership/entity/Membership.java, src/main/java/com/example/connect/domain/membership/repository/MembershipRepository.java, src/main/java/com/example/connect/domain/membership/service/MembershipService.java, src/main/java/com/example/connect/domain/user/controller/UserController.java, src/main/java/com/example/connect/domain/user/dto/UserResDto.java, src/main/java/com/example/connect/global/config/SchedulerConfig.java
멤버십 취소 기능 구현
- 멤버십 취소 후 만료기간 지날 경우 카드 데이터, 멤버십 정보 삭제
=> feat: 멤버십 제거 기능 구현

src/main/java/com/example/connect/domain/membership/controller/MembershipController.java, src/main/java/com/example/connect/domain/membership/entity/Membership.java, src/main/java/com/example/connect/domain/membership/repository/MembershipRepository.java, src/main/java/com/example/connect/domain/membership/service/MembershipService.java, src/main/java/com/example/connect/global/error/errorcode/ErrorCode.java
[프리미엄 -> 노말]
- 만료일 지날 경우 결제
[노말 -> 프리미엄]
- 바로 결제
- 사용일수분 만큼 감산 후 결제(1의자리에서 버림 처리)
변경될 멤버십이 있을 경우 -> 에러 발생
=> feat: 멤버십 업데이트 기능 구현

src/main/java/com/example/connect/domain/chat/ChatDeadLetterRetry.java, src/main/java/com/example/connect/domain/chat/ChatPublisher.java, src/main/java/com/example/connect/domain/chat/ChatSubscriber.java, src/main/java/com/example/connect/domain/chat/dto/ChatRabbimqRestDto.java, src/main/java/com/example/connect/global/config/RabbitMQConfig.java, src/main/resources/application.properties
[#197](https://github.com/alsqja/Connect/issues/197)
=> feat: 채팅 RabbitMQ Retry 로직 작성

src/main/java/com/example/connect/domain/couponuser/repository/CustomCouponUserRepositoryImpl.java, src/main/java/com/example/connect/domain/payment/controller/AdminPaymentController.java, src/main/java/com/example/connect/domain/payment/dto/AdminPaymentChartResDto.java, src/main/java/com/example/connect/domain/payment/repository/PaymentRepository.java, src/main/java/com/example/connect/domain/payment/service/AdminPaymentService.java
=> feat: 매출 통계 조회 구현
